language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.12"

before_install:
  - "npm install -g grunt-cli"

before_script:
  - "gem install travis-artifacts"

after_success:
  - "travis-artifacts upload --path build/melonJS-2.2.0.js --target-path artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER"

env:
  global:
  - "ARTIFACTS_S3_BUCKET=melonjs-builds"
  - "ARTIFACTS_AWS_REGION=us-east-1"
  - secure: eIJEcZUfQet6hdDVoYQnoqMMKt9B7EaJtcnVp6GCsvQbDTlLPc1JCSa+iDcicp0podlayEb5Ovd7kcq+LJ7fvQx23UG2XFuVa9KpnYk4tLQ6wev/nYR7738KvECqDBTwyalF9E8uSS8WsGSG+PN2cb2s4IWWe2IQYEfPPjcniUI=
  - secure: grcjulMlTuO7l0HLme6IazVRfq4pzZhjdsfu/5ZoUyTsZZQIUcbxN4uW3PIRwZFU85BC0blJi+un5sT8SyWIzCJNVZeyJp5NyzuH2PlWupiNH4d7Pxs44EjvivXNKfHbFJDogGg9gRM1TgnGDEUGo/HD8ZGDRJc1DAqpcWfBQU0=
